[unstable]
build-std = ["core", "compiler_builtins","alloc"]
build-std-features = ["compiler-builtins-mem"]
# allows us to specify json target 
# (without it causing issues on my machine, please check once on your machine if it breaks)
# remove below line if causing issues, but it should be fine
json-target-spec = true  

[build]
target = "osTarget.json"

[target.'cfg(target_os="none")']
runner="bootimage runner"